In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['SimHei']  # 用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False  # 用来正常显示负号

# 创建张量的基本方法
print("创建张量的基本方法:")
x = torch.tensor([1, 2, 3])
print(f"从列表创建: {x}")

x = torch.zeros(3, 2)
print(f"全零张量: \n{x}")

x = torch.ones(2, 3)
print(f"全一张量: \n{x}")

x = torch.rand(2, 2)
print(f"随机张量(0-1均匀分布): \n{x}")

x = torch.randn(2, 2)
print(f"随机张量(标准正态分布): \n{x}")

# 张量的数据类型
print("\n张量的数据类型:")
x = torch.tensor([1, 2, 3], dtype=torch.float32)
print(f"float32类型: {x}, 数据类型: {x.dtype}")

x = torch.tensor([1, 2, 3], dtype=torch.int64)
print(f"int64类型: {x}, 数据类型: {x.dtype}")

x = torch.tensor([True, False, True], dtype=torch.bool)
print(f"布尔类型: {x}, 数据类型: {x.dtype}")


# 张量的基础运算
print("\n张量的基础运算:")
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

print(f"加法: {a + b}")
print(f"减法: {a - b}")
print(f"乘法(元素级): {a * b}")
print(f"除法: {a / b}")

# 矩阵运算
print("\n矩阵运算:")
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"矩阵乘法: \n{torch.matmul(a, b)}")
print(f"矩阵转置: \n{a.T}")

# 广播机制
print("\n广播机制:")
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
b = torch.tensor([10, 20, 30], dtype=torch.float32)
print(f"广播加法: \n{a + b}")

创建张量的基本方法:
从列表创建: tensor([1, 2, 3])
全零张量: 
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
全一张量: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
随机张量(0-1均匀分布): 
tensor([[0.3460, 0.7363],
        [0.5983, 0.3678]])
随机张量(标准正态分布): 
tensor([[-0.1834, -1.1945],
        [-1.2590, -0.7724]])

张量的数据类型:
float32类型: tensor([1., 2., 3.]), 数据类型: torch.float32
int64类型: tensor([1, 2, 3]), 数据类型: torch.int64
布尔类型: tensor([ True, False,  True]), 数据类型: torch.bool

张量的基础运算:
加法: tensor([5., 7., 9.])
减法: tensor([-3., -3., -3.])
乘法(元素级): tensor([ 4., 10., 18.])
除法: tensor([0.2500, 0.4000, 0.5000])

矩阵运算:
矩阵乘法: 
tensor([[19., 22.],
        [43., 50.]])
矩阵转置: 
tensor([[1., 3.],
        [2., 4.]])

广播机制:
广播加法: 
tensor([[11., 22., 33.],
        [14., 25., 36.]])


In [3]:
# 更多数学操作
# 创建3行2列和2行3列的tensor
tensor_3x2 = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
tensor_2x3 = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)
# 执行矩阵乘法
print("矩阵乘法(3x2 @ 2x3):", torch.matmul(tensor_3x2, tensor_2x3))
print("求和:", a.sum())
print("平均值:", a.mean())
print("最大值:", a.max())
print("最小值:", a.min())
print("绝对值:", a.abs())
# print("形状变化后的元素级乘法:", tensor_3x2 * tensor_2x3)

矩阵乘法(3x2 @ 2x3): tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
求和: tensor(21.)
平均值: tensor(3.5000)
最大值: tensor(6.)
最小值: tensor(1.)
绝对值: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
# 从NumPy数组创建
np_array = np.array([1, 2, 3])
tensor_from_np = torch.from_numpy(np_array)
print("从NumPy创建:", tensor_from_np)
print('tensor_to_numpy:', tensor_from_np.numpy())

从NumPy创建: tensor([1, 2, 3], dtype=torch.int32)
tensor_to_numpy: [1 2 3]


In [5]:
# 形状操作
print("\n=== 张量形状操作 ===")
tensor = torch.rand(2, 3, 4)
print("原始张量形状:", tensor.shape)
print("张量维度数:", tensor.dim())
print("张量元素总数:", tensor.numel())

# 形状变换
reshaped = tensor.reshape(4, 6)
print("重塑后形状:", reshaped.shape)
print("展平后:", tensor.flatten().shape)
print("维度扩展:", tensor.unsqueeze(0).shape)  # 在第0维添加维度
print("维度压缩:", tensor[:, 0:1, :].squeeze(1).shape)  # 压缩大小为1的维度 


=== 张量形状操作 ===
原始张量形状: torch.Size([2, 3, 4])
张量维度数: 3
张量元素总数: 24
重塑后形状: torch.Size([4, 6])
展平后: torch.Size([24])
维度扩展: torch.Size([1, 2, 3, 4])
维度压缩: torch.Size([2, 4])


In [6]:

# 索引和切片
print("\n=== 索引与切片 ===")
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原矩阵:\n", matrix)
print("第1行:", matrix[0])
print("第2列:", matrix[:, 1])
print("子矩阵:", matrix[0:2, 1:3])
print('matrix[[0,2], [1,2]]',matrix[[0,2], [1,2]])

# 高级索引
indices = torch.tensor([0, 2])
print("选择特定行:", matrix[indices])
mask = matrix > 5
print("布尔掩码索引:", matrix[mask])



=== 索引与切片 ===
原矩阵:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
第1行: tensor([1, 2, 3])
第2列: tensor([2, 5, 8])
子矩阵: tensor([[2, 3],
        [5, 6]])
matrix[[0,2], [1,2]] tensor([2, 9])
选择特定行: tensor([[1, 2, 3],
        [7, 8, 9]])
布尔掩码索引: tensor([6, 7, 8, 9])


In [7]:
# 高级索引
indices = torch.tensor([0, 2])
print("选择特定行:", matrix[indices])
mask = matrix > 5
print("布尔掩码索引:", matrix[mask]) 


选择特定行: tensor([[1, 2, 3],
        [7, 8, 9]])
布尔掩码索引: tensor([6, 7, 8, 9])


In [8]:
print(torch.Tensor([1]).item()) #获取一个tensor中的元素值

1.0


In [9]:
t2 =np.array([[[3,4]]])
print('t2.shape',t2.shape)
b=t2.reshape([2, -1]) # -1表示自动计算
print(b)
print('-'*50)
print(f'id(t2)={id(t2)},id(b)={id(b)}') #t2的形状并没有发生改变
b[0][0] = 100
print(b)
print(t2)

t2.shape (1, 1, 2)
[[3]
 [4]]
--------------------------------------------------
id(t2)=1602902461296,id(b)=1603632478032
[[100]
 [  4]]
[[[100   4]]]


In [13]:
t2 = torch.Tensor([[[3,4]]])
print('t2.shape',t2.shape)
b=t2.view([2, -1]) # -1表示自动计算
print(b)
print('-'*50)
print(f'id(t2)={id(t2)},id(b)={id(b)}') #t2的形状并没有发生改变

t2.shape torch.Size([1, 1, 2])
tensor([[3.],
        [4.]])
--------------------------------------------------
id(t2)=1603633130512,id(b)=1603633130912


In [14]:
b[0][0] = 100
print(b)
print(t2)

tensor([[100.],
        [  4.]])
tensor([[[100.,   4.]]])


In [15]:
t2.untyped_storage().untyped().data_ptr() == b.untyped_storage().untyped().data_ptr() #判断两个tensor是否共享内存

True

# 运算函数加下划线与不加的区别

In [16]:
# 不带下划线的方法（sub）返回一个新的张量，不会修改原始张量
a = torch.tensor([10, 20, 30])
b = torch.tensor([1, 2, 3])
c = a.sub(b)  # 等价于 c = a - b

print("原始张量 a:", a)
print("新张量 c = a.sub(b):", c)
print("a ",a)

print("-" * 50)

# 带下划线的方法（sub_）会直接修改原始张量（即原地操作）
a = torch.tensor([10, 20, 30])
b = torch.tensor([1, 2, 3])
a.sub_(b)  # 等价于 a -= b

print("执行 a.sub_(b) 后的 a:", a)
print("原地操作后 a 已被修改")

原始张量 a: tensor([10, 20, 30])
新张量 c = a.sub(b): tensor([ 9, 18, 27])
a  tensor([10, 20, 30])
--------------------------------------------------
执行 a.sub_(b) 后的 a: tensor([ 9, 18, 27])
原地操作后 a 已被修改
