In [1]:
import numpy as np     #只需要下载numpy库即可
import random
import GridWorld_v1

In [ ]:
gamma = 0.9   #折扣因子，越接近0越近视
rows = 5      #记得行数和列数这里要同步改
columns = 5
# gridworld = GridWorld_v1.GridWorld_v1(rows=rows, columns=columns, forbiddenAreaNums=4, targetNums=2, seed = random.randint(1,1000))
# gridworld = GridWorld_v1.GridWorld_v1(desc = [".#",".T"])             #赵老师4-1的例子
# gridworld = GridWorld_v1.GridWorld_v1(desc = ["##.T","...#","...."])  #随便弄的例子
gridworld = GridWorld_v1.GridWorld_v1(forbiddenAreaScore=-10, score=1,desc = [".....",".##..","..#..",".#T#.",".#..."]) 
gridworld.show()

value = np.zeros(rows*columns)       #初始化可以任意，也可以全0，这就是state-value
qtable = np.zeros((rows*columns,5))  #初始化，这里主要是初始化维数，里面的内容会被覆盖所以无所谓,这里的5是action的数量,这里的qtable就是Q表格,这里是action-value shape=(rows*columns,5)
policy = np.argmax(qtable,axis=1)    #初始策略，这里是贪心策略，即选择Q值最大的动作
gridworld.showPolicy(policy)         #打印初始策略


⬜️⬜️⬜️⬜️⬜️
⬜️🚫🚫⬜️⬜️
⬜️⬜️🚫⬜️⬜️
⬜️🚫✅🚫⬜️
⬜️🚫⬜️⬜️⬜️
⬆️⬆️⬆️⬆️⬆️
⬆️⏫️⏫️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⏫️✅⏫️⬆️
⬆️⏫️⬆️⬆️⬆️


In [ ]:
pre_value = value.copy()+1           #随便弄个不一样的初值

gridworld.show()                     #打印gridworld
gridworld.showPolicy(policy)         #打印策略

cnt = 0                              #防止死循环，不需要也可以（因为可以证明必定收敛）
while(np.sum((pre_value-value)**2)>0.001): 
    print("Euclidean Distance:",np.sum((pre_value-value)**2))  #计算欧几里得距离
    pre_value = value.copy()         #保存副本，方便前后对比

    cnt = cnt+1                      #防止死循环
    if cnt>100:                      
        break
        
    for i in range(rows * columns):  #当前状态Si
        nowx = i // columns          #坐标x
        nowy = i % columns           #坐标y 但都没用上
        
        for j in range(5): # 5个action
            score,nextState = gridworld.getScore(i,j)        #获取Si状态中，执行动作j后的（得分，下一个状态）
            qtable[i][j] = score + gamma * value[nextState]  #开始迭代，更新qtable，q=r+gamma*V(S')

    policy = np.argmax(qtable,axis=1) #这个就是策略了，policy update，但是value-iteration，
                                      #因为这里的策略是百分百选argmax的，别的概率是0，所以可以直接忽略策略的不确定性
    value = np.max(qtable,axis=1)     #更新value 向量,对应伪代码的value update,因为最大的q值的action是最优策略，概率为1

    print(np.round(value.reshape(rows,columns), 1))  
    gridworld.showPolicy(policy)     #打印策略
print(np.round(value.reshape(rows,columns), 1))  #打印value,并四舍五入到小数点后一位-
print(policy)

⬜️⬜️⬜️⬜️⬜️
⬜️🚫🚫⬜️⬜️
⬜️⬜️🚫⬜️⬜️
⬜️🚫✅🚫⬜️
⬜️🚫⬜️⬜️⬜️
⬆️⬆️⬆️⬆️⬆️
⬆️⏫️⏫️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⏫️✅⏫️⬆️
⬆️⏫️⬆️⬆️⬆️
Euclidean Distance: 25.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0.]]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬆️
⬆️⏩️⬆️➡️⬆️
Euclidean Distance: 5.0
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  1.9 0.  0. ]
 [0.  1.9 1.9 1.9 0. ]
 [0.  0.9 1.9 0.9 0. ]]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬆️
⬆️⏩️⬆️⬅️⬆️
Euclidean Distance: 5.67
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  2.7 0.  0. ]
 [0.  2.7 2.7 2.7 0. ]
 [0.  1.7 2.7 1.7 0.8]]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬆️
⬆️⏩️⬆️⬅️⬅️
Euclidean Distance: 5.248800000000001
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  3.4 0.  0. ]
 [0.  3.4 3.4 3.4 0.7]
 [0.  2.4 3.4 2.4 1.5]]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬇️
⬆️⏩️⬆️⬅️⬅️
Euclidean Distance: 4.782969000000001
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  4.1 0.  0.7]
 [0.  4.1 4.1 4.1 1.4]
 [0.  3.1

In [4]:
print('⬜️🚫')
print('⬜️✅')
print('⬆️➡️⬇️⬅️🔄')
print('⏫︎⏩️⏪🔄✅')

tmp = "⏫︎⏩️⏬⏪🔄"
print(tmp[0])
print(tmp[1])
print(tmp[2])

⬜️🚫
⬜️✅
⬆️➡️⬇️⬅️🔄
⏫︎⏩️⏪🔄✅
⏫
︎
⏩
